name: Golang Formatter
on: [pull_request]
jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      package: src/github.com/${{ github.repository }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/${{ env.package }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Golang Formatter
      uses: sladyn98/auto-go-format@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
